### ISSUE TITLE
添加账号执行命令 小大写区分

### ISSUE THREAD

**Issue by dingyuan408** [radondb/xenon#117]
kubectl exec -ti <pod-name> -c krypton /krypton/kryptoncli mysql createuser <user> <host> <password> <YES/NO>
kubectl exec -ti <pod-name> -c krypton /krypton/kryptoncli mysql createsuperuser <user> <host> <password> <YES/NO> #
![image](https://user-images.githubusercontent.com/80507309/113113953-7051c700-923d-11eb-9f7c-9b2086c708f4.png)

**Comment by TCeason** [comment]
If you use `YES`, it allows you to create a user with SSL.


But if do not use `YES`, just use other words like yes, Yes, no, No and more. It will allow you to create a user.
