### ISSUE TITLE
[bug] listen endpoint panic but program still run

### ISSUE THREAD

**Issue by zhyass** [radondb/xenon#124]
The config json file:
```
"server": {
	"endpoint": "test-krypton-1.test-krypton.default:8801"
},
```

When the container start, get error logs:
```
2021/04/16 03:18:29.911339 trace.go:32:      [WARNING]  FOLLOWER[ID:test-krypton-1.test-krypton.default:8801, V:0, E:0].state.init
2021/04/16 03:18:29.913554 server.go:186:       [PANIC]    server.rpc.start.error[listen tcp: lookup test-krypton-1.test-krypton.default on 10.96.0.10:53: no such host
xbase/xrpc.(*Service).Start
    /go/src/github.com/radondb/xenon/src/xbase/xrpc/xrpc.go:54
server.(*Server).Start
    /go/src/github.com/radondb/xenon/src/server/server.go:185
main.main
    /go/src/github.com/radondb/xenon/src/xenon/xenon.go:79
runtime.main
    /usr/local/go/src/runtime/proc.go:203
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1357]
```

According to normal logic, the program should exit at this time. Actually xenon still run because of the code [recover() ](https://github.com/radondb/xenon/blob/master/src/server/server.go#L166) , but we cannot listen the endpoint.

**Comment by zhyass** [comment]
Currently we want to use the `publishNotReadyAddresses` parameter in kubernetes to be able to access pods even if the pod is not ready. From this issue, even if this parameter is used, we may still need to wait up to 30s.

**Comment by andyli029** [comment]
Good job.
