### ISSUE TITLE
创建数据库会卡死

### ISSUE THREAD

**Issue by dulumao** [radondb/xenon#15]
A,B,C 主机做了集群后，在D机器，做了radon,在E机器，连接D 主机创建的radon proxy后,进入mysql console,执行sql创建数据就卡死了

**Comment by dulumao** [comment]
FOLLOWER[ID:172.24.12.79:8801, V:0, E:0].init.my.gtid.is:{ 4  false No false No  2d4ed046-f73d-11e7-b455-00163e069ce5:1-1040   Slave failed to initialize relay log info structure from the repository  Slave failed to initialize relay log info structure from the repository}

**Comment by hustjieke** [comment]
Would you please provide the execution logs on machine D? It will be helpful to analyse the problem you had met. Besides, we hope you can use English to communicate so that anyone else can understand your description of the problem.
