### ISSUE TITLE
xenon -c /etc/xenon/xenon.json启动报错

### ISSUE THREAD

**Issue by Myshiner** [radondb/xenon#164]
用/usr/local/xenon/bin/xenon -c /etc/xenon/xenon.json > /etc/xenon/log/xenon.log 2>&1 &
启动时报错:
cat /etc/xenon/log/xenon.log
xenon:[{Tag: Time:2022/08/04 04:48:36 Git: GoVersion:go1.12.4 Platform:linux amd64}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x776ef6]

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0x0, 0x931a74, 0x1a, 0xc0000c9e28, 0x1, 0x1)
        /usr/local/xenon/src/xbase/xlog/xlog.go:137 +0x26
main.main()
        /usr/local/xenon/src/xenon/xenon.go:54 +0x3de

xenon版本是1.1.4，go版本是1.12.4(换成go1.18.1问题依旧)

**Comment by Myshiner** [comment]
找到原因了，是因为加了注释的原因

**Comment by KID-G** [comment]
> 找到原因了，是因为加了注释的原因

好的。
