### ISSUE TITLE
Xenon集群除了Master以外，另外两个节点log-bin无法备份

### ISSUE THREAD

**Issue by peniridis** [radondb/xenon#22]
## 查看集群状态
./xenoncli cluster mysql
+-------------------+----------+-------+-----------+------------------------+----------------+
|        ID         |   Raft   | Mysql |  Option   |  Master_Log_File/Pos   | IO/SQL_Running | Seconds_Behind |
+-------------------+----------+-------+-----------+------------------------+----------------+
| 168.5.80.101:8801   | LEADER   | ALIVE | READWRITE | [mysql-bin.000012/194] | [true/true]    |     
+-------------------+----------+-------+-----------+------------------------+----------------+
| 168.5.80.110:8801  | FOLLOWER | ALIVE | READONLY  | [/4]                                | [false/true]     | 
+-------------------+----------+-------+-----------+------------------------+----------------+
| 168.5.80.94:8801   | FOLLOWER | ALIVE | READONLY  | [/4]                                 | [false/true]     |  
+-------------------+----------+-------+-----------+------------------------+----------------+
## 无法同步Slave节点日志
 2018/08/30 09:21:47.256256       [INFO]        server.mysql.wait.for.work[maxwait:60s]
 **2018/08/30 09:21:47.259514       [INFO]        mysql.slave.status:&{ 4  false No false No  befc84a7-ab60-11e8-bf7c-005056896b97:1-8     }**
 2018/08/30 09:21:47.259545       [INFO]        server.mysql.gtid:{Master_Log_File: Read_Master_Log_Pos:4 Relay_Master_Log_File: Slave_IO_Running:false Slave_IO_Running_Str:No Slave_SQL_Running:false Slave_SQL_Running_Str:No Retrieved_GTID_Set: Executed_GTID_Set:befc84a7-ab60-11e8-bf7c-005056896b97:1-8 Seconds_Behind_Master: Slave_SQL_Running_State: Last_Error: Last_IO_Error: Last_SQL_Error:}
 2018/08/30 09:21:47.259549       [INFO]        server.mysql.set.to.READONLY
 2018/08/30 09:21:47.259802       [INFO]        server.mysql.start.slave
 2018/08/30 09:21:47.410705       [INFO]        server.mysql.check.replication.user...
 2018/08/30 09:21:47.410993       [INFO]        server.mysql.setup.done
 2018/08/30 09:21:47.410999       [INFO]        server.prepare.setup.RPC
 2018/08/30 09:21:47.411180       [INFO]        server.RPC.setup.done
 2018/08/30 09:21:47.411209       [INFO]        mysqld[/etc/my.cnf].monitor.start...
 2018/08/30 09:21:47.411216       [INFO]        mysql[localhost:3306].startping...
 2018/08/30 09:21:47.411224       [INFO]        FOLLOWER[ID:168.5.80.94:8801, V:0, E:0].raft.start...
 2018/08/30 09:21:47.411277       [WARNING]     xrpc.Start.listening.on[168.5.80.94:8801]
 2018/08/30 09:21:47.411280       [INFO]        server.start.success...
 2018/08/30 09:21:47.411283       [INFO]        xenon.start.success...
## 配置
三个节点xenon配置几乎一样

        "replication":
        {
                "user":"root",
                "passwd":"123456"
        },
        "backup":
        {
                "ssh-host":"168.5.80.94",
                "ssh-user":"root",
                "ssh-passwd":"",
                "basedir":"/usr/local/mysql",
                "backupdir":"/opt/xenon/data/mysql",
                "xtrabackup-bindir":"/opt/xenon",
                "backup-iops-limits":100000,
                "backup-use-memory": "2GB",
                "backup-parallel": 2
        },
## 其他
不知道怎么排查问题，以及提供什么信息才能表述清楚。

**Comment by lunsir** [comment]
从当前状态看来是从节点的IO线程不工作了，现在的./xenoncli cluster status 和./xenoncli cluster gtid 是什么情况？

**Comment by NigrumIris** [comment]
## GTID状态
./xenoncli cluster gtid 
+-------------------+----------+-------+--------------------------------------------+-------------
|        ID         |   Raft   | Mysql |             Executed_GTID_Set              | Retrieved_GTID_Set |
+-------------------+----------+-------+--------------------------------------------+-------------
| 168.5.80.101:8801 | FOLLOWER | ALIVE | c21a82c1-ab34-11e8-b056-005056896d74:1-7   |                    
+-------------------+----------+-------+--------------------------------------------+-------------
| 168.5.80.110:8801 | FOLLOWER | ALIVE | 7e5ddd8a-ac23-11e8-a21f-005056892236:1-3   |                    
+-------------------+----------+-------+--------------------------------------------+-------------
| 168.5.80.94:8801  | LEADER   | ALIVE | 3e5daae4-ac08-11e8-b227-005056896b97:1-9,␤ |                    
|-------------------|-----------| -------| 973e8493-ac07-11e8-b5a5-005056896b97:1-5,␤ |                    
| -------------------| ----------| -------| bce6f394-ac1e-11e8-a7d9-005056896b97:1-6   |                    
+-------------------+----------+-------+--------------------------------------------+-------------
## 集群状态
./xenoncli cluster status
同样也是从节点**IO/SQL_RUNNING**状态为[false/true]，
## 补充
1. 将主节点人为切换到其他从节点后仍然只有主节点的IO状态为true
2. 目前测试环境为三台centos7 ，参考配置目测是Ubuntu，请问这块有影响吗；
3. 同时翻阅代码，`bash -c /usr/local/mysql/bin/mysqld_safe --defaults-file=/etc/my.cnf > /dev/null&`这块命令在centos7 下运行超时，个人认为加上nohup启动就不会在mysqld.go的第64行抛出err，类似问题是否有影响。
@lunsir

**Comment by lunsir** [comment]
由于你这几个库刚开始都执行了几个事务导致没办法做主从了，两个从节点都执行下reset master应该就可以了

**Comment by NigrumIris** [comment]
## 半同步复制配置问题
|------------------------------|------------|
| Variable_name                          | Value      |
|-------------------------------|------------|
| rpl_semi_sync_master_enabled| ON         |
| rpl_semi_sync_slave_enabled| ON         |
再问提个问题 ；）
以上所有节点是否都需要启用这两个配置

**Comment by lunsir** [comment]
这个东西代码会判断如果是主自动打开master_enabled,从自动打开slave_enabled.不需要手动管理。
