### ISSUE TITLE
Xenon startup failure 

### ISSUE THREAD

**Issue by Fuck7Qyou** [radondb/xenon#32]
下面是报错日志和配置文件，数据库都是初始化安装，没有配置主从关系 ，普通用户启动xenon的 

[xenon.json.txt](https://github.com/radondb/xenon/files/2571147/xenon.json.txt)
[xenon.txt](https://github.com/radondb/xenon/files/2571150/xenon.txt)

请氙研发同学帮忙解决！ thanks

**Comment by BohuTANG** [comment]
Hi,

From the xenon.txt,  it seems that the mysqld starts error, so first to confirm your mysql starts ok:
```
/data/mysql-master/bin/mysqld_safe --defaults-file=/data/mysql-master/my.cnf
```

**Comment by Fuck7Qyou** [comment]
hi
不是mysqld启动错误，mysql是正常的，主要的报错是以下
   [ERROR]       server.mysql.start.slave.error[Error 1200: The server is not configured as slave; fix in config file or with CHANGE MASTER TO]

 [ERROR]       FOLLOWER[ID:10.10.0.117:8801, V:0, E:0].leaderStartShellCommand[[-c sudo  ip a d 10.10.0.250/32 dev eth0]].out[bash -c sudo  ip a d 10.10.0.250/32 dev eth0RTNETLINK answers: Cannot assign requested address

[xenon.txt](https://github.com/radondb/xenon/files/2571514/xenon.txt)

请氙研发同学帮忙解决！谢谢

**Comment by Fuck7Qyou** [comment]
日志报错，说是没有配置主从mysql关系，
[错误] server.mysql.start.slave.error [错误1200：服务器未配置为slave; 修复配置文件或使用CHANGE MASTER TO]
但是官方说是：xenon使用配置文件xenon.conf.json。存储库包含一个名为conf / xenon-sample.conf.json的文件，其中包含sic设置。Xenon非常智能，它不需要你对MySQL做任何事情。只需要安装MySQL服务。

**Comment by BohuTANG** [comment]
Hi,

Please cover your password with mosaics in xenon.txt(remove and re-attach).
Then attach your mysql config file.

**Comment by Fuck7Qyou** [comment]
拓扑描述：
10.10.0.117 db01(hostname) ---- (主库)
10.10.0.117 db02 (hostname)---- （从库1）
10.10.0.242 db03(hostname) ----（从库2）
下面是3节点的配置文件;
[xenon.conf-1.txt](https://github.com/radondb/xenon/files/2574228/xenon.conf-1.txt)
[xenon.conf-2.txt](https://github.com/radondb/xenon/files/2574229/xenon.conf-2.txt)
[xenon.conf-3.txt](https://github.com/radondb/xenon/files/2574230/xenon.conf-3.txt)
下面是报错日志：
[xenon1.txt](https://github.com/radondb/xenon/files/2574232/xenon1.txt)
[xenon2.txt](https://github.com/radondb/xenon/files/2574233/xenon2.txt)
[xenon3.txt](https://github.com/radondb/xenon/files/2574234/xenon3.txt)
下面是mysql配置文件：
[mysql-1.txt](https://github.com/radondb/xenon/files/2574236/mysql-1.txt)
[mysql-2.txt](https://github.com/radondb/xenon/files/2574237/mysql-2.txt)
[xenon3.txt](https://github.com/radondb/xenon/files/2574238/xenon3.txt)

主要报错信息：
 server.mysql.start.slave.error[Error 1200: The server is not configured as slave; fix in config file or with CHANGE MASTER TO]
FOLLOWER[ID:10.10.0.117:8801, V:0, E:0].leaderStartShellCommand[[-c sudo  ip a d 10.10.0.250/32 dev eth0]].out[bash -c sudo  ip a d 10.10.0.250/32 dev eth0RTNETLINK answers: Cannot assign requested address

请xenon研发同学帮忙解决！！！

**Comment by Fuck7Qyou** [comment]
hi
FOLLOWER[ID:10.10.0.117:8801, V:0, E:0].peers.json.file[raft.meta/peers.json].does.not.exist  
日志说没有peers.json这个文件, 请问这个文件是启动的时候自动生成还是自己配置的，官方文档没有说要配置这个文件？
请氙研发同学帮忙解决！

**Comment by Fuck7Qyou** [comment]
hi
还有，ip a d 创建的vip ，用arping  vip   Cannot assign requested address

FOLLOWER[ID:10.10.0.117:8801, V:0, E:0].leaderStartShellCommand[[-c sudo  ip a d 10.10.0.250/32 dev eth0]].out[bash -c sudo  ip a d 10.10.0.250/32 dev eth0RTNETLINK answers: Cannot assign requested address
请氙研发同学帮忙解决！ thanks

**Comment by BohuTANG** [comment]
Hi @Fuck7Qyou ,

Please the xenon guideline first:
https://github.com/radondb/xenon/blob/master/docs/how_to_build_and_run_xenon.md
