### ISSUE TITLE
[question] 基于xenon的mysql集群vip没有指定主库

### ISSUE THREAD

**Issue by Fuck7Qyou** [radondb/xenon#33]
拓扑描述：
192.168.36.115    master（主机名）----（主库）
192.168.36.116    slave   （主机名）----（从库1）
192.168.36.117    normal（主机名）----（从库2）

vip：192.168.36.200

下面是3节点的配置文件：
[xenon1.txt](https://github.com/radondb/xenon/files/2594428/xenon1.txt)
[xenon2.txt](https://github.com/radondb/xenon/files/2594429/xenon2.txt)
[xenon3.txt](https://github.com/radondb/xenon/files/2594430/xenon3.txt)

下面是keepalived配置文件：
[keepalived1.txt](https://github.com/radondb/xenon/files/2594431/keepalived1.txt)
[keepalived2.txt](https://github.com/radondb/xenon/files/2594432/keepalived2.txt)

集群状态 ：
![1111](https://user-images.githubusercontent.com/44251514/48695941-7b32d080-ec1b-11e8-8307-48b7587910f6.png)

问题描述：
![1111](https://user-images.githubusercontent.com/44251514/48696044-c51bb680-ec1b-11e8-9294-24db2fd1aefc.png)
因为每次通过VIPvip打开一个新的连接，mysql主机都改变，没有办法确通过VIP连接的一定是主库，而且后期我想通过proxysql做读写分离，proxysql是基于端口或者sql语句进行读写分离。但是我的mysql集群都基于xenon的搭建的，只有一个VIP和一个端口进行连接的，而且是访问后端mysql是轮询模式，怎么实现读写分离？

请研发氙的同学帮忙解决一下。 thanks

**Comment by TCeason** [comment]
Hi , 读写分离 和 xenon 是两回事。可以研究一下 lvs

**Comment by Fuck7Qyou** [comment]
hi，我想问的是，xenon集群的数据库是通过vip来访问的，因为是轮询的，如果连接到从库，那么写的sql语句就写不进去了。那么怎么通过连接vip区分它们是从库还是主库？

**Comment by Fuck7Qyou** [comment]
Hi ，例如：我想通过vip 去访问数据库，只有master能写，其他不能写。
![1111](https://user-images.githubusercontent.com/44251514/48744818-cb557580-eca3-11e8-89b5-44aeeedebe08.png)
很显然通vip来执行sql语句是不行的，怎么解决这问题？
请氙研发的同学帮忙解决一下。谢谢

**Comment by TCeason** [comment]
我想了解一下，是不是只配置了一个 vip 192.168.36.200 ？ 这个IP 是在 all nodes 去轮循的。可以作为读IP。如果想要写 ip ，需要在 xenon.json 里面配置	
你的配置：
```
"leader-start-command":"sudo ip a a 192.168.36.200/32 dev ens3  && sudo arping -c 3 -A  192.168.36.200  -I ens3  ",
```

* 我建议，在这里，把 36.200 改成 36.201 或者其他的，由这个 IP 作为高可用写IP

**Comment by Fuck7Qyou** [comment]
是只配置了一个vip，这个ip是在所有节点轮询的。  如果按照你的意思说是要配置两个vip吗，一个做可读，一个只做可写，但是怎么在配置文件改。   如果把36.200，改成其他的，也是只有一个vip啊，也是轮询的。所以还是不能确定哪个ip是可读，哪个是可写？  那客户端还是没法连接集群

**Comment by Fuck7Qyou** [comment]
hi， 除了这个，还有哪些架构是mysql高可用和读写分离可以部署在云主机上的，lvs云主机上不支持，请推荐一下。

**Comment by TCeason** [comment]
可以参见这种方式创建[云主机](https://docs.qingcloud.com/product/computing/instance#%E4%B8%BB%E6%9C%BAinstance)。

建议选择 Ubuntu Server 16.04.4 LTS 64bit
