### ISSUE TITLE
[question] 客户端怎么连接基于xenon搭建mysql集群

### ISSUE THREAD

**Issue by Fuck7Qyou** [radondb/xenon#34]
嗨，例如：我想通过vip去访问数据库，只有主能写，其他不能写。 很显然通过vip来执行sql语句是不行的，怎么解决这问题？ 请氙研发的同学帮忙解决一下。谢谢

![1111](https://user-images.githubusercontent.com/44251514/48811907-d7583a80-ed6a-11e8-9de7-2e0a96d43a0d.png)

**Comment by TCeason** [comment]
参见：https://github.com/radondb/xenon/issues/33#issuecomment-440558489
