### ISSUE TITLE
[question] 请问xenon可以管理一台服务器上的多个实例不？

### ISSUE THREAD

**Issue by DrLimd** [radondb/xenon#37]
请问xenon可以管理一台服务器上的多个实例不？如果可以，怎么配置呢？

**Comment by BohuTANG** [comment]
Hi,

Exactly, no.
xenon is design for container instance, if we run many xenons on one server, the xenon may kill others mysqld:
https://github.com/radondb/xenon/blob/2ba83a5ee81da115763231db951b96e9316c186b/src/mysqld/linux_args.go#L81

So, we must keep every mysql config name is unique, but I am not sure it works well.
