### ISSUE TITLE
[feature] Add invalid state

### ISSUE THREAD

**Issue by TCeason** [radondb/xenon#67]
## Summary 

MySQL ueses Engine commit（If MySQL trx prepare and flush to data, it will be committed. ） to protect data security. But it may not be suite for MySQL Cluster. 

## Fix 

1. Add invalid state （Invalid should not send a agree vote）
2. If check Engine commit , set the node status to invalid（use gtid_sub function, so we also need check gtid when raft election）

## Question 

1. If xenon dead, the state may be confusion, so we should record all state into a file.

**Comment by BohuTANG** [comment]
ACK

**Comment by TCeason** [comment]
ADD:

The Invalid state should not return ok to CANDICATEs , may be return ErrorInvalidRequest (or ErrorInvalidGtid)?

@BohuTANG

**Comment by BohuTANG** [comment]
ACK
